const MARKET_STATES = {
  volatilityRising: '波动率开始上升',
  lowIvHighRv: '低 IV + 高 RV 预期',
  highIvFalling: '高 IV + 预期回落',
  rangeBound: '区间震荡',
  nearFlatFarVol: '近端横盘 + 远端保留波动',
  trendStarting: '单边趋势开始',
  hedgeExistingPosition: '已有底仓需要保护',
  bullishSynthetic: '偏多合成与结构增强',
};

const STRATEGY_TYPES = {
  longVol: '买入波动率',
  shortVol: '卖出波动率',
  longDirection: '买入方向',
  sellerIncome: '卖方收租',
  timeStructure: '时间结构',
  rangeStructure: '区间结构',
  trendSpread: '趋势价差',
  hedge: '底仓保护',
  syntheticLong: '合成多头',
  courseCombo: '课程组合结构',
};

const OPTIONS_STRATEGY_CATALOG = [
  {
    id: 'long-straddle',
    nameZh: '买入跨式',
    nameEn: 'long straddle',
    marketStates: [MARKET_STATES.volatilityRising],
    strategyTypes: [STRATEGY_TYPES.longVol],
    whenToUse: '预期行情会大幅波动，方向暂时不明确，且实际波动有机会跑赢买入成本。',
    setup: ['买入同一到期日、同一行权价的 call', '买入同一到期日、同一行权价的 put'],
    operationSteps: ['判断 IV 是否仍有上升空间', '确认事件或行情能带来足够 RV', '选择流动性好的平值行权价', '同时买入 call 和 put', '持仓中观察价格是否快速远离行权价', '当单边盈利覆盖双腿成本或 IV 明显回落时处理仓位'],
    coreGreeks: ['gamma', 'vega', 'theta'],
    risks: ['横盘消耗权利金', 'IV 回落抵消价格波动', '盈亏平衡点距离过远'],
    sourceLessons: ['day3'],
    keywords: ['long straddle', 'straddle', '跨式', '买波动', '买入跨式'],
    imageHints: ['assets/payoffs/volatility-structures-grid.png', 'assets/day3/WechatIMG30.jpg'],
  },
  {
    id: 'long-strangle',
    nameZh: '买入宽跨式',
    nameEn: 'long strangle',
    marketStates: [MARKET_STATES.volatilityRising],
    strategyTypes: [STRATEGY_TYPES.longVol],
    whenToUse: '预期大波动，愿意用更远的盈亏平衡点换更低初始成本。',
    setup: ['买入较高行权价 call', '买入较低行权价 put', '两条腿同标的、同到期'],
    operationSteps: ['判断行情是否可能突破外侧行权价', '选择两侧流动性足够的虚值腿', '计算上下两个盈亏平衡点', '同时买入 call 和 put', '持仓中观察价格是否靠近任一外侧腿', '波动兑现后处理盈利腿或整体退出'],
    coreGreeks: ['gamma', 'vega', 'theta'],
    risks: ['需要更大价格移动', '双腿同时被 theta 消耗', 'IV 回落导致估值下降'],
    sourceLessons: ['day3'],
    keywords: ['long strangle', 'strangle', '宽跨', '买入宽跨', '买波动'],
    imageHints: ['assets/payoffs/volatility-structures-grid.png', 'assets/day3/WechatIMG30.jpg'],
  },
  {
    id: 'short-straddle',
    nameZh: '卖出跨式',
    nameEn: 'short straddle',
    marketStates: [MARKET_STATES.highIvFalling, MARKET_STATES.rangeBound],
    strategyTypes: [STRATEGY_TYPES.shortVol, STRATEGY_TYPES.sellerIncome],
    whenToUse: '预期价格围绕平值区域震荡，IV 偏高且可能回落。',
    setup: ['卖出同一到期日、同一行权价的 call', '卖出同一到期日、同一行权价的 put'],
    operationSteps: ['确认 IV 偏高且趋势突破风险可控', '选择平值附近行权价', '计算双边最大可承受波动范围', '同时卖出 call 和 put', '持仓中观察任一侧 delta 和 gamma 扩张', '达到目标权利金比例或区间失效时退出'],
    coreGreeks: ['theta', 'vega', 'gamma'],
    risks: ['两侧尾部风险', '单边突破后负 gamma 放大', '保证金压力上升'],
    sourceLessons: ['day3'],
    keywords: ['short straddle', '卖出跨式', '卖跨式', '卖波动', 'straddle'],
    imageHints: ['assets/payoffs/volatility-structures-grid.png', 'assets/day3/WechatIMG30.jpg'],
  },
  {
    id: 'short-strangle',
    nameZh: '卖出宽跨式',
    nameEn: 'short strangle',
    marketStates: [MARKET_STATES.highIvFalling, MARKET_STATES.rangeBound],
    strategyTypes: [STRATEGY_TYPES.shortVol, STRATEGY_TYPES.sellerIncome],
    whenToUse: '预期价格留在较宽区间内，想用更外侧短腿收取时间价值。',
    setup: ['卖出较高行权价 call', '卖出较低行权价 put', '两条腿同标的、同到期'],
    operationSteps: ['确定上下边界', '选择距离当前价格较远的短 call 和短 put', '检查净收入与保证金', '预设危险侧处理方式', '持仓中观察价格靠近哪一侧短腿', '收到目标权利金比例或突破区间时处理仓位'],
    coreGreeks: ['theta', 'vega', 'gamma'],
    risks: ['区间外单边行情', '短腿接近后亏损扩张', '宽区间带来风险麻痹'],
    sourceLessons: ['day3'],
    keywords: ['short strangle', '卖出宽跨', '卖宽跨', '卖波动', 'strangle'],
    imageHints: ['assets/payoffs/volatility-structures-grid.png', 'assets/day3/WechatIMG30.jpg'],
  },
  {
    id: 'calendar-spread',
    nameZh: '日历价差',
    nameEn: 'calendar spread',
    marketStates: [MARKET_STATES.nearFlatFarVol],
    strategyTypes: [STRATEGY_TYPES.timeStructure],
    whenToUse: '预期近端围绕目标行权价震荡，同时远端时间价值或波动率仍有保留价值。',
    setup: ['卖出近月期权', '买入远月同一行权价期权', '通常同为 call 或同为 put'],
    operationSteps: ['选择目标停留价位', '检查近月 theta 是否足够', '检查远月 vega 和流动性', '建立近月空腿和远月多腿', '持仓中观察短 gamma 风险', '近腿衰减后平仓或滚动'],
    coreGreeks: ['theta', 'vega', 'gamma'],
    risks: ['近端强单边突破', 'delta neutral 被误读为无方向风险', '远月 IV 回落'],
    sourceLessons: ['day4'],
    keywords: ['calendar spread', 'calendar', '日历价差', '日历', '近月', '远月'],
    imageHints: ['assets/payoffs/calendar-vs-diagonal-grid.png'],
  },
  {
    id: 'diagonal-spread',
    nameZh: '对角价差',
    nameEn: 'diagonal spread',
    marketStates: [MARKET_STATES.nearFlatFarVol, MARKET_STATES.trendStarting],
    strategyTypes: [STRATEGY_TYPES.timeStructure, STRATEGY_TYPES.trendSpread],
    whenToUse: '既想吃近端时间价值，又对方向有明确倾斜。',
    setup: ['买入远月一条腿', '卖出近月另一条腿', '两条腿到期不同、行权价不同'],
    operationSteps: ['确认方向偏多或偏空', '选择远月主腿', '选择近月收租腿并留出安全距离', '检查净 delta 和短腿风险', '持仓中观察短腿是否受压', '方向失效或短腿突破时调整'],
    coreGreeks: ['delta', 'theta', 'vega', 'gamma'],
    risks: ['短腿被快速穿越', '方向倾斜判断错误', '远腿成本过高'],
    sourceLessons: ['day4'],
    keywords: ['diagonal spread', 'diagonal', '对角价差', '对角', '日历'],
    imageHints: ['assets/payoffs/calendar-vs-diagonal-grid.png'],
  },
  {
    id: 'butterfly',
    nameZh: '蝶式策略',
    nameEn: 'butterfly',
    marketStates: [MARKET_STATES.rangeBound],
    strategyTypes: [STRATEGY_TYPES.rangeStructure],
    whenToUse: '预期到期时价格钉在某个中间价附近，追求有限风险的精确区间收益。',
    setup: ['买入 1 张低行权价 call', '卖出 2 张中间行权价 call', '买入 1 张高行权价 call', '三档同标的、同到期'],
    operationSteps: ['确定目标中间价', '选择上下翼宽度', '检查净成本或净收入', '建立 1-2-1 结构', '持仓中观察价格是否靠近中间价', '价格明显远离目标区时退出或调整'],
    coreGreeks: ['theta', 'gamma', 'delta'],
    risks: ['目标价判断过窄', '价格远离中间价', '临期 gamma 变化快'],
    sourceLessons: ['day5'],
    keywords: ['butterfly', '蝶式', '1-2-1', '中间价', '钉住'],
    imageHints: ['assets/payoffs/long-butterfly-payoff.png'],
  },
  {
    id: 'collar',
    nameZh: '领口策略',
    nameEn: 'collar',
    marketStates: [MARKET_STATES.hedgeExistingPosition],
    strategyTypes: [STRATEGY_TYPES.hedge],
    whenToUse: '已经持有现货或期货多头，希望锁下方风险，并愿意让出一部分上方收益。',
    setup: ['持有底仓多头', '买入下方 put', '卖出上方 call'],
    operationSteps: ['确认底仓需要保护的时间窗口', '选择下方保护价', '选择可接受的上方让利价', '用卖 call 收入补贴买 put 成本', '持仓中观察底仓和期权组合总盈亏', '风险解除或上方被突破时处理期权腿'],
    coreGreeks: ['delta', 'vega', 'theta'],
    risks: ['上方收益被封顶', '保护期限覆盖不足', '下方保护成本过高'],
    sourceLessons: ['day6'],
    keywords: ['collar', '领口', '保护', 'protective', '底仓', '保险'],
    imageHints: ['assets/payoffs/collar-payoff.png', 'assets/day6/collar-zero-cost.png'],
  },
  {
    id: 'put-spread-collar',
    nameZh: '区间化领口',
    nameEn: 'put-spread collar',
    marketStates: [MARKET_STATES.hedgeExistingPosition],
    strategyTypes: [STRATEGY_TYPES.hedge, STRATEGY_TYPES.rangeStructure],
    whenToUse: '底仓只需要保护一段明确下跌区间，希望进一步压低保险成本。',
    setup: ['持有底仓多头', '下方用 bear put spread 保护一段下跌', '上方卖 call 补贴成本'],
    operationSteps: ['确认要保护的下跌区间', '买入较高行权价 put', '卖出较低行权价 put', '卖出上方 call', '检查跌破保护下沿后的剩余底仓风险', '风险解除或区间变化时退出'],
    coreGreeks: ['delta', 'theta', 'vega'],
    risks: ['跌破低行权价后保护变弱', '上方让利', '保护区间设置过窄'],
    sourceLessons: ['day10'],
    keywords: ['put-spread collar', '区间化', 'collar', 'bear put spread', '领口'],
    imageHints: ['assets/payoffs/collar-payoff.png', 'assets/payoffs/bullish-bearish-spreads-grid.png'],
  },
  {
    id: 'gamma-scalping',
    nameZh: 'Gamma Scalping',
    nameEn: 'gamma scalping',
    marketStates: [MARKET_STATES.lowIvHighRv],
    strategyTypes: [STRATEGY_TYPES.longVol],
    whenToUse: 'IV 相对低，预期 RV 更高，市场有来回摆动，且交易成本可控。',
    setup: ['买入正 gamma 期权核心腿', '用期货或现货动态对冲净 delta'],
    operationSteps: ['确认 IV 较低且未来可能有真实波动', '选择正 gamma 核心腿', '建立期货或现货对冲工具', '价格摆动后按净 delta 调整线性腿', '记录再平衡收益是否覆盖 theta 和费用', '波动消失或时间消耗过快时退出'],
    coreGreeks: ['gamma', 'delta', 'theta', 'vega'],
    risks: ['震荡幅度覆盖不了成本', '对冲频率和滑点损耗', '时间价值持续消耗'],
    sourceLessons: ['day6'],
    keywords: ['gamma scalping', '正 gamma', 'gamma', '动态对冲', 'delta hedge'],
    imageHints: ['assets/day6/gamma-scalping-flow.png', 'assets/payoffs/gamma-scalping-core.png'],
  },
  {
    id: 'iron-condor',
    nameZh: '铁鹰策略',
    nameEn: 'iron condor',
    marketStates: [MARKET_STATES.rangeBound, MARKET_STATES.highIvFalling],
    strategyTypes: [STRATEGY_TYPES.shortVol, STRATEGY_TYPES.rangeStructure],
    whenToUse: '预期价格留在明确上下边界内，IV 有回落空间，想双边收租并封顶亏损。',
    setup: ['下方建立 bull put spread', '上方建立 bear call spread', '四条腿同标的、同到期'],
    operationSteps: ['判断区间上下边界', '选择到期日', '确定上下短腿', '买入两侧保护长腿封顶风险', '检查净收入和最大亏损比例', '持仓观察危险侧和 IV 回落', '达到目标权利金比例或区间失效时退出'],
    coreGreeks: ['theta', 'vega', 'gamma'],
    risks: ['单边突破区间', '最大亏损大于权利金收入', '危险侧处理太慢'],
    sourceLessons: ['day11'],
    keywords: ['iron condor', '铁鹰', '铁鹰策略', 'condor', '区间收租'],
    imageHints: ['assets/strategy/spread-payoffs.png'],
  },
  {
    id: 'bull-call-spread',
    nameZh: '牛市认购价差',
    nameEn: 'bull call spread',
    marketStates: [MARKET_STATES.trendStarting],
    strategyTypes: [STRATEGY_TYPES.trendSpread, STRATEGY_TYPES.longDirection],
    whenToUse: '温和看涨，希望降低买 call 成本，并接受上方盈利封顶。',
    setup: ['买入较低行权价 call', '卖出较高行权价 call', '两条腿同标的、同到期'],
    operationSteps: ['确认看涨目标区', '买入低行权价 call', '卖出高行权价 call 补贴成本', '检查最大盈利和最大亏损', '持仓中观察价格是否接近上方短腿', '到目标区或方向失效时退出'],
    coreGreeks: ['delta', 'theta', 'gamma'],
    risks: ['上方收益封顶', '慢涨仍可能被 theta 消耗', '短腿管理不及时'],
    sourceLessons: ['day9', 'day10'],
    keywords: ['bull call spread', '牛市认购', '认购牛市价差', 'call spread'],
    imageHints: ['assets/payoffs/bullish-bearish-spreads-grid.png'],
  },
  {
    id: 'bull-put-spread',
    nameZh: '牛市认沽价差',
    nameEn: 'bull put spread',
    marketStates: [MARKET_STATES.trendStarting],
    strategyTypes: [STRATEGY_TYPES.trendSpread, STRATEGY_TYPES.sellerIncome],
    whenToUse: '中性偏多或趋势向上，希望用正 theta 的价差结构参与行情。',
    setup: ['卖出较高行权价 put', '买入较低行权价 put', '两条腿同标的、同到期'],
    operationSteps: ['确认偏多趋势或潜力区条件', '选择短 put 行权价', '买入更低行权价 put 封顶风险', '检查净权利金和最大亏损', '上涨后观察是否滚动短腿', '方向失效或短腿受压时处理'],
    coreGreeks: ['theta', 'delta', 'gamma'],
    risks: ['跌破短 put 后亏损扩大', '滚动路径依赖', '保留低价值 put 的收益需要后续反转'],
    sourceLessons: ['day10'],
    keywords: ['bull put spread', '牛市认沽', '认沽牛市价差', 'put spread'],
    imageHints: ['assets/payoffs/bullish-bearish-spreads-grid.png', 'assets/day10/WechatIMG82.jpg'],
  },
  {
    id: 'bear-put-spread',
    nameZh: '熊市认沽价差',
    nameEn: 'bear put spread',
    marketStates: [MARKET_STATES.trendStarting, MARKET_STATES.hedgeExistingPosition],
    strategyTypes: [STRATEGY_TYPES.trendSpread, STRATEGY_TYPES.hedge],
    whenToUse: '温和看跌，或只想保护一段明确下跌区间。',
    setup: ['买入较高行权价 put', '卖出较低行权价 put', '两条腿同标的、同到期'],
    operationSteps: ['确认下跌目标区', '买入高行权价 put', '卖出低行权价 put 降低成本', '检查保护下沿和净成本', '价格进入目标区后止盈或完成保护', '跌破低行权价后重新评估保护缺口'],
    coreGreeks: ['delta', 'theta', 'gamma'],
    risks: ['更深下跌保护被截断', '方向不到时净成本消耗', '保护区间选窄'],
    sourceLessons: ['day10'],
    keywords: ['bear put spread', '熊市认沽', '认沽熊市价差', '熊市价差', '做空的价差', '买高卖低', 'bear spread'],
    imageHints: ['assets/payoffs/bullish-bearish-spreads-grid.png'],
  },
  {
    id: 'risk-reversal',
    nameZh: '风险逆转',
    nameEn: 'risk reversal',
    marketStates: [MARKET_STATES.bullishSynthetic],
    strategyTypes: [STRATEGY_TYPES.syntheticLong, STRATEGY_TYPES.courseCombo],
    whenToUse: '偏多观点强，希望用卖 put 补贴买 call，并接受下方义务。',
    setup: ['买入虚值 call', '卖出虚值 put', '通常选择相近 delta 的两条腿'],
    operationSteps: ['确认强偏多方向', '选择目标 call', '选择可承担义务的 put', '检查净成本或净收入', '持仓中观察下方 short put 风险', '方向兑现或下方风险上升时处理'],
    coreGreeks: ['delta', 'vega', 'theta'],
    risks: ['下跌时 short put 成为主要风险', '保证金压力', '把偏斜指标和结构名称混淆'],
    sourceLessons: ['day13'],
    keywords: ['risk reversal', '风险逆转', '25 delta', '偏斜', 'synthetic'],
    imageHints: ['assets/day13/WechatIMG106.jpg'],
  },
  {
    id: 'synthetic-long-stock',
    nameZh: '合成多头',
    nameEn: 'synthetic long stock',
    marketStates: [MARKET_STATES.bullishSynthetic],
    strategyTypes: [STRATEGY_TYPES.syntheticLong],
    whenToUse: '希望用期权组合合成接近持有标的的线性多头暴露。',
    setup: ['买入同一行权价 call', '卖出同一行权价 put', '两条腿同标的、同到期'],
    operationSteps: ['确认需要线性多头暴露', '选择同一行权价和到期日', '买入 call 并卖出 put', '检查保证金和下方风险', '持仓中观察净 delta 是否接近多头', '方向兑现或风险上升时整体处理'],
    coreGreeks: ['delta', 'theta', 'vega'],
    risks: ['下跌体验接近持有标的多头', 'short put 保证金压力', '到期处理要求高'],
    sourceLessons: ['day13'],
    keywords: ['synthetic long', 'synthetic long stock', '合成多头', '合成股票'],
    imageHints: ['assets/day13/WechatIMG107.jpg'],
  },
  {
    id: 'bullish-crab',
    nameZh: '看涨螃蟹',
    nameEn: 'bullish crab',
    marketStates: [MARKET_STATES.bullishSynthetic, MARKET_STATES.rangeBound],
    strategyTypes: [STRATEGY_TYPES.courseCombo, STRATEGY_TYPES.rangeStructure],
    whenToUse: '偏多但希望通过身体、租金和远端腿组合，兼顾稳定和右侧爆发。',
    setup: ['用价差身体承接主体结构', '用近端租金补贴', '保留远端 call 爆发腿'],
    operationSteps: ['确认偏多结构需要', '搭建价差身体', '配置近端收租腿', '配置远端 call', '观察身体稳定性和远端腿价值', '趋势变化时调整租金腿或远端腿'],
    coreGreeks: ['delta', 'theta', 'gamma', 'vega'],
    risks: ['课程结构执行偏差', '租金腿和远端腿管理复杂', '行情停滞拖累远端腿'],
    sourceLessons: ['day11'],
    keywords: ['看涨螃蟹', '螃蟹', 'crab', '远端 call', '租金'],
    imageHints: ['assets/day11/WechatIMG91.jpg'],
  },
  {
    id: 'ratio-spread',
    nameZh: '比例价差',
    nameEn: 'ratio spread',
    marketStates: [MARKET_STATES.trendStarting, MARKET_STATES.bullishSynthetic],
    strategyTypes: [STRATEGY_TYPES.trendSpread, STRATEGY_TYPES.courseCombo],
    whenToUse: '偏多爆发观点较强，希望右侧突破后多腿接管利润。',
    setup: ['卖出 1 张较低行权价 call', '买入 2 张较高行权价 call'],
    operationSteps: ['确认上方爆发目标', '选择短 call 行权价', '选择更高行权价的两张长 call', '检查中间区域亏损', '价格冲过上方后观察长 call 接管程度', '价格卡在中间区域时处理'],
    coreGreeks: ['delta', 'gamma', 'theta'],
    risks: ['中间区域亏损', '方向慢导致时间损耗', '腿数比例管理复杂'],
    sourceLessons: ['day12'],
    keywords: ['比例价差', 'ratio spread', '卖 1', '买 2', 'ratio'],
    imageHints: ['assets/day12/WechatIMG98.jpg'],
  },
  {
    id: 'bull-three-leg',
    nameZh: '牛三腿',
    nameEn: 'bull three-leg',
    marketStates: [MARKET_STATES.bullishSynthetic],
    strategyTypes: [STRATEGY_TYPES.courseCombo, STRATEGY_TYPES.sellerIncome],
    whenToUse: '偏多但节奏不确定，想同时收租、吃慢涨，并保留后续调比例能力。',
    setup: ['下方卖 put', '上方卖 call', '中间买一张偏实值或近平值 call'],
    operationSteps: ['确认偏多但节奏未完全明朗', '选择下方 short put', '选择中间 long call', '选择上方 short call', '检查组合总 Greeks', '横盘时收租、慢涨时保留主梁、快涨时处理上方短腿'],
    coreGreeks: ['delta', 'gamma', 'theta', 'vega'],
    risks: ['下方 short put 风险', '上方 short call 压住趋势', '比例调整慢'],
    sourceLessons: ['day13'],
    keywords: ['牛三腿', '三腿', 'long call', 'short put', 'short call'],
    imageHints: ['assets/day13/WechatIMG108.jpg'],
  },
  {
    id: 'alligator-strategy',
    nameZh: '鳄鱼策略',
    nameEn: 'alligator strategy',
    marketStates: [MARKET_STATES.trendStarting, MARKET_STATES.bullishSynthetic],
    strategyTypes: [STRATEGY_TYPES.trendSpread, STRATEGY_TYPES.courseCombo],
    whenToUse: '偏多趋势启动，希望左侧亏损有限，中间利润上升更快，右侧继续保留斜率。',
    setup: ['以 bull call spread 为身体', '额外增加一条 long call', '通过短 call 控制部分时间价值'],
    operationSteps: ['确认趋势启动信号', '建立 bull call spread', '增加额外 long call 增强右侧', '检查净成本和上方斜率', '持仓中观察趋势速度和 theta', '方向失效或结构降档时退出'],
    coreGreeks: ['delta', 'gamma', 'theta'],
    risks: ['净成本更高', '方向慢或 IV 回落拖累结构', '课程名称和标准术语映射需要保留来源'],
    sourceLessons: ['day13'],
    keywords: ['鳄鱼', 'alligator', 'bull call spread', 'extra long call', '右侧'],
    imageHints: ['assets/day13/WechatIMG109.jpg'],
  },
];

module.exports = {
  MARKET_STATES,
  OPTIONS_STRATEGY_CATALOG,
  STRATEGY_TYPES,
};
